Repository andela/wger-kronos, pull requests merged in 2019-06, with the labels that each got.

#13 [#166239312] Set up Heroku deployment
  .bowerrc
  .eslintignore
  .eslintrc.json
  .gitignore
  .travis.yml
  Procfile
  app.json
  bower.json
  package-lock.json
  package.json
  requirements.txt
  settings.py
  wger/core/templates/mobile/template.html
  wger/core/templates/template.html
  wger/core/templates/template_features.html
  wger/settings_global.py
Labels: Done, Review Required

#12 #166185727 Cache nutritional values for plan
  wger/nutrition/__init__.py
  wger/nutrition/models.py
  wger/nutrition/signals.py
  wger/nutrition/tests/test_cache_nutrional.py
  wger/utils/cache.py
Labels: Review Required

#14 #166185744 Rework landing page - Give value on the landing page
  requirements.txt
  settings.py
  wger/core/templates/template_features.html
  wger/software/static/css/styles.css
  wger/software/static/images/gym_management.jpg
  wger/software/templates/features.html
Labels: Review Required

#16 #166185745 Enable social logins with Google and Facebook
  Procfile
  requirements.txt
  wger/core/templates/base.html
  wger/core/templates/template.html
  wger/settings_global.py
  wger/urls.py
Labels: Done

#19 #166581814 Fix heroku review apps
  .bowerrc
  .gitignore
  app.json
  package-lock.json
  package.json
  requirements.txt
Labels: Done, Review Required

#17 #166466377 Show application navigation menu
  .bowerrc
  Procfile
  bower.json
  package-lock.json
  package.json
  startup
  wger/core/templates/base.html
  wger/core/templates/mobile/template.html
  wger/core/templates/template.html
  wger/core/templates/template_features.html
  wger/core/templates/user/login.html
Labels: Done, Review Required

#9 #166185728 Show all infos for an exercise
  .travis.yml
  wger/exercises/api/serializers.py
  wger/exercises/api/views.py
  wger/exercises/tests/test_exercise.py
  wger/exercises/urls.py
  wger/exercises/views/exercises.py
  wger/urls.py
Labels: Done, Review Required

#15 #166185729 Allow creation of users via REST API
  .eslintignore
  .gitignore
  requirements.txt
  settings.py
  wger/config/migrations/0001_initial.py
  wger/config/migrations/0002_auto_20190612_1819.py
  wger/core/api/serializers.py
  wger/core/api/views.py
  wger/core/management/commands/add-user-rest-api.py
  wger/core/management/commands/list-user-rest-api.py
  wger/core/migrations/0001_initial.py
  wger/core/migrations/0002_auto_20141225_1512.py
  wger/core/migrations/0003_auto_20150217_1554.py
  wger/core/migrations/0004_auto_20150217_1914.py
  wger/core/migrations/0005_auto_20151025_2236.py
  wger/core/migrations/0006_auto_20151025_2237.py
  wger/core/migrations/0007_repetitionunit.py
  wger/core/migrations/0008_weightunit.py
  wger/core/migrations/0009_auto_20160303_2340.py
  wger/core/migrations/0010_auto_20190611_1259.py
  wger/core/models.py
  wger/core/tests/test_api_user.py
  wger/core/urls.py
  wger/email/migrations/0001_initial.py
  wger/email/migrations/0002_auto_20190612_1819.py
  wger/exercises/migrations/0004_auto_20190612_1819.py
  wger/gym/migrations/0007_auto_20190612_1819.py
  wger/manager/migrations/0008_auto_20190612_1819.py
  wger/nutrition/migrations/0002_auto_20190612_1819.py
  wger/urls.py
Labels: Done, Review Required

#21 #166185732 Reset exercise cache on muscle delete
  Procfile
  wger/exercises/models.py
  wger/exercises/views/muscles.py
Labels: Done, Review Required

#24 #166670291 Add coverage badge
  .coveralls.yml
  .travis.yml
  README.rst
Labels: Done, Review Required

#20 #166185733 Make translations of exercises and ingredients easier
  wger/exercises/tests/test_corrected_exercise.py
  wger/exercises/tests/test_exercise.py
  wger/exercises/views/exercises.py
  wger/nutrition/models.py
  wger/nutrition/tests/test_ingredient.py
  wger/nutrition/views/ingredient.py
Labels: Done, Review Required

#22 #166185734 Relation between workout log and session
  wger/manager/migrations/0008_auto_20190613_1013.py
  wger/manager/models.py
  wger/manager/tests/test_weight_log.py
Labels: Done, Review Required

#30 #166812919 Fix failing Travis build
  .travis.yml
  wger/manager/migrations/0009_merge.py
Labels: Done, Review Required

#27 #166787340 Fix show gym users
  wger/core/fixtures/test-user-data.json
  wger/gym/tests/test_members_list.py
  wger/gym/views/gym.py
Labels: Done, Review Required

#25 #166185743 Allow managers deactivate trainers from a gym
  .coveragerc
  wger/core/views/user.py
  wger/gym/templates/gym/member_list.html
  wger/gym/tests/test_user.py
Labels: Done, Review Required

#29 #166185746 Enable getting exercises for a body part when the mouse hovers over the body part
  wger/exercises/templates/exercise/overview.html
Labels: Done, Review Required
